---
- method: "GET"
  path: "caches"
  name: "caches"
  endpointType: "Endpoint"
  signature: "CachesEndpoint.caches()"
  owner: "org.springframework.boot.actuate.cache.CachesEndpoint"
  returnType: "CachesReport"
  casEndpoint: false
  summary: "Provides access to the application창\x80\x99s caches."
- method: "GET"
  path: "caches/{cache}"
  name: "caches"
  endpointType: "Endpoint"
  signature: "CachesEndpoint.cache(java.lang.String,java.lang.String)"
  owner: "org.springframework.boot.actuate.cache.CachesEndpoint"
  returnType: "CacheEntry"
  casEndpoint: false
  summary: "Provides access to the application창\x80\x99s caches."
- method: "DELETE"
  path: "caches/{cache}"
  name: "caches"
  endpointType: "Endpoint"
  signature: "CachesEndpoint.clearCache(java.lang.String,java.lang.String)"
  owner: "org.springframework.boot.actuate.cache.CachesEndpoint"
  returnType: "boolean"
  casEndpoint: false
  summary: "Provides access to the application창\x80\x99s caches."
- method: "DELETE"
  path: "caches"
  name: "caches"
  endpointType: "Endpoint"
  signature: "CachesEndpoint.clearCaches()"
  owner: "org.springframework.boot.actuate.cache.CachesEndpoint"
  casEndpoint: false
  summary: "Provides access to the application창\x80\x99s caches."
